amostras/amostras/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sedimentos/', include('sedimentos.urls')),
    url(r'^',include('sedimentos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amostras/sedimentos/urls.py
from django.conf.urls import url
from . import views

app_name = 'sedimentos'

urlpatterns = [

    # se refere a /resident/
    url(r'^$', views.index, name='index'),
    url(r'^$', views.amostra, name='amostra'),
    # se refere a uma em especifico/
    url(r'^(?P<amostra_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_amostra/$', views.create_amostra, name='create_amostra'),
    url(r'^(?P<amostra_id>[0-9]+)/delete_amostra/$', views.delete_amostra, name='delete_amostra'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),


    # se refere a uma em especifico/
    url(r'^(?P<continente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'continente/add/$', views.create_continente, name='create_continente'),
    url(r'continente/(?P<pk>[0-9]+)/$', views.delete_continente, name='delete_continente'),


    # se refere a uma em especifico/
    url(r'^(?P<cidade_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'cidade/add/$', views.create_cidade, name='create_cidade'),
    url(r'cidade/(?P<pk>[0-9]+)/$', views.delete_cidade, name='delete_cidade'),


    # se refere a uma em especifico/
    url(r'^(?P<estado_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'estado/add/$', views.create_estado, name='create_estado'),
    url(r'estado/(?P<pk>[0-9]+)/$', views.delete_estado, name='delete_estado'),


    # se refere a uma em especifico/
    url(r'^(?P<país_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'país/add/$', views.create_país, name='create_país'),
    url(r'país/(?P<pk>[0-9]+)/$', views.delete_país, name='delete_país'),

    # se refere a uma em especifico/
    url(r'^(?P<ambiente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'ambiente/add/$', views.create_ambiente, name='create_ambiente'),
    url(r'ambiente/(?P<pk>[0-9]+)/$', views.delete_ambiente, name='delete_ambiente'),

    # se refere a uma em especifico/
    url(r'^(?P<clima_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'clima/add/$', views.create_clima, name='create_clima'),
    url(r'clima/(?P<pk>[0-9]+)/$', views.delete_clima, name='delete_clima'),

    # se refere a uma em especifico/
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^inicial/$', views.inicial, name='inicial'),
    url(r'^contato/$', views.contato, name='contato'),
    url(r'^adicionar/$', views.adicionar, name='adicionar'),
    url(r'^agradecimentos/$', views.agradecimentos, name='agradecimentos'),
    url(r'^register/$', views.register, name='register'),
    # filtros/
    url(r'^continentes/(?P<filter_by>[a-zA_Z]+)/$', views.continentes, name='continentes'),
    url(r'^estados/(?P<filter_by>[a-zA_Z]+)/$', views.estados, name='estados'),
    url(r'^cidades/(?P<filter_by>[a-zA_Z]+)/$', views.cidades, name='cidades'),
    url(r'^paíss/(?P<filter_by>[a-zA_Z]+)/$', views.paíss, name='paíss'),
    url(r'^climas/(?P<filter_by>[a-zA_Z]+)/$', views.climas, name='climas'),
    url(r'^ambientes/(?P<filter_by>[a-zA_Z]+)/$', views.ambientes, name='ambientes'),
    url(r'^amostras/(?P<filter_by>[a-zA_Z]+)/$', views.amostras, name='amostras'),

]


amostras/sedimentos/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Amostra,Continente,País,Estado,Cidade,Ambiente,Clima



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']



class ContatoForm(forms.Form):
    Nome = forms.CharField(label='Nome', max_length=100, required=True)
    Email = forms.EmailField(label=' Email', max_length=200, required=True)
    Mensagem = forms.CharField(label=' Mensagem', min_length=100, required=True, widget=forms.Textarea)




class amostraForm(forms.ModelForm):
    class Meta:
        model =Amostra
        fields = ['codigo','coletador', 'descrição', 'tipo', 'data', 'granulometria','imagem','imagem1','imagem2','imagem3','imagem4','imagem5','imagem6','imagem7','imagem8']



class continenteForm(forms.ModelForm):
    class Meta:
        model =Continente
        fields = ['amostra', 'nome', 'sigla']



class paísForm(forms.ModelForm):
    class Meta:
        model =País
        fields = ['amostra', 'continente', 'nome', 'região']



class estadoForm(forms.ModelForm):
    class Meta:
        model =Estado
        fields = ['amostra', 'continente', 'país', 'nome']



class cidadeForm(forms.ModelForm):
    class Meta:
        model =Cidade
        fields = ['amostra', 'continente', 'país', 'estado', 'nome', 'geologia']



class ambienteForm(forms.ModelForm):
    class Meta:
        model =Ambiente
        fields = ['amostra', 'continente', 'país', 'estado', 'cidade', 'tipo']




class climaForm(forms.ModelForm):
    class Meta:
        model =Clima
        fields = ['amostra', 'continente', 'país', 'estado', 'cidade', 'tipo']

amostras/sedimentos/views.py
from django.shortcuts import  render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.views.generic import View
from .models import Amostra
from .models import Continente
from .models import Cidade
from .models import Estado
from .models import País
from .models import Ambiente
from .models import Clima
from .forms import UserForm, ContatoForm, amostraForm, continenteForm, paísForm, estadoForm, cidadeForm,climaForm,ambienteForm
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.template import Context
from django.db.models import Q


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def create_amostra(request):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
        form = amostraForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            amostra = form.save(commit=False)
            amostra.user = request.user
            amostra.imagem = request.FILES['imagem']
            file_type = amostra.imagem.url.split('.')[-1]
            amostra.imagem1 = request.FILES['imagem1']
            amostra.imagem2 = request.FILES['imagem2']
            amostra.imagem3 = request.FILES['imagem3']
            amostra.imagem4 = request.FILES['imagem4']
            amostra.imagem5 = request.FILES['imagem5']
            amostra.imagem6 = request.FILES['imagem6']
            amostra.imagem7 = request.FILES['imagem7']
            amostra.imagem8 = request.FILES['imagem8']


            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'amostra': amostra,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'sedimentos/amostra_form.html', context)
            amostra.save()
            return render(request, 'sedimentos/detail.html', {'amostra': amostra})
        context = {
            "form": form,
        }
        return render(request, 'sedimentos/amostra_form.html', context)



def delete_amostra(request, amostra_id):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
     amostra = Amostra.objects.get(pk=amostra_id)
     amostra.delete()
     amotras = amostra.objects.filter(user=request.user)
     return render(request, 'sedimentos/index.html', {'amostras': amotras})

def detail(request, amostra_id):
        user = request.user
        amostra = get_object_or_404(Amostra, pk=amostra_id)
        return render(request, 'sedimentos/detail.html', {'amostra': amostra, 'user': user})



########################################################################################################################
########################################################################################################################
########################################################################################################################

def create_continente(request):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
        form = continenteForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            continente = form.save(commit=False)
            continente.user = request.user
            continente.save()
            return render(request, 'sedimentos/detail.html', {continente: continente})
        context = {
            "form": form,
        }
        return render(request, 'sedimentos/continente_form.html', context)


def delete_continente(request, continente_id):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
     amostra = get_object_or_404(Amostra, pk=amostra_id)
     continente = Continente.objects.get(pk=continente_id)
     continente.delete()
     return render(request, 'sedimentos/index.html', {'amostra':amostra})


########################################################################################################################
########################################################################################################################
########################################################################################################################



def create_cidade(request):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
        form = cidadeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            cidade = form.save(commit=False)
            cidade.user = request.user
            cidade.save()
            return render(request, 'sedimentos/detail.html', {cidade: cidade})
        context = {
            "form": form,
        }
        return render(request, 'sedimentos/cidade_form.html', context)


def delete_cidade(request, cidade_id):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
     amostra = get_object_or_404(Amostra, pk=amostra_id)
     cidade = Cidade.objects.get(pk=cidade_id)
     cidade.delete()
     return render(request, 'sedimentos/index.html', {'amostra': amostra})


########################################################################################################################
########################################################################################################################
########################################################################################################################


def create_estado(request):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
        form = estadoForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            estado = form.save(commit=False)
            estado.user = request.user
            estado.save()
            return render(request, 'sedimentos/detail.html', {estado: estado})
        context = {
            "form": form,
        }
        return render(request, 'sedimentos/estado_form.html', context)


def delete_estado(request, estado_id):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
     amostra = get_object_or_404(Amostra, pk=amostra_id)
     estado = Estado.objects.get(pk=estado_id)
     estado.delete()
     return render(request, 'sedimentos/index.html', {'amostra': amostra})
########################################################################################################################
########################################################################################################################
########################################################################################################################



def create_país(request):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
        form = paísForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            país = form.save(commit=False)
            país.user = request.user
            país.save()
            return render(request, 'sedimentos/detail.html', {país: país})
        context = {
            "form": form,
        }
        return render(request, 'sedimentos/país_form.html', context)


def delete_país(request, país_id):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
     amostra = get_object_or_404(Amostra, pk=amostra_id)
     país = País.objects.get(pk=país_id)
     país.delete()
     return render(request, 'sedimentos/index.html', {'amostra': amostra})

########################################################################################################################
########################################################################################################################
########################################################################################################################

def create_ambiente(request):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
        form = ambienteForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            ambiente = form.save(commit=False)
            ambiente.user = request.user
            ambiente.save()
            return render(request, 'sedimentos/detail.html', {ambiente: ambiente})
        context = {
            "form": form,
        }
        return render(request, 'sedimentos/ambiente_form.html', context)


def delete_ambiente(request, ambiente_id):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
     amostra = get_object_or_404(Amostra, pk=amostra_id)
     ambiente = Ambiente.objects.get(pk=ambiente_id)
     ambiente.delete()
     return render(request, 'sedimentos/index.html', {'amostra': amostra})

########################################################################################################################
########################################################################################################################
########################################################################################################################

def create_clima(request):
    if not request.user.is_authenticated():
        return render(request, 'sedimentos/login.html')
    else:
        form = climaForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            clima = form.save(commit=False)
            clima.user = request.user
            clima.save()
            return render(request, 'sedimentos/detail.html', {clima: clima})
        context = {

amostras/templates/sedimentos/adicionar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block tutle %}SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS{% endblock %}</title>
    {% load staticfiles %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'sedimentos/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <tr>
       <td width="180" rowspan="3" align="center">
            <a href="http://www5.usp.br/" target="_blank">
             <img src="/static/sedimentos/imagens/usp.png" width="150" height="70" alt="" border="0" style="position: relative; top: -3px;">

            </a>
       </td>
       <td width="180" rowspan="3" align="center">
            <a href="http://www.igc.usp.br/" target="_blank">
            <img src="/static/sedimentos/imagens/logo_IGc.png" width="150" height="70" alt="" border="0" style="position: relative; top: -3px;">
            </a>
       </td>
       <td width="180" rowspan="3" align="center">
            <a href="https://www.ime.usp.br/" target="_blank">
            <img src="/static/sedimentos/imagens/imeusp.png" width="150" height="70" alt="" border="0" style="position: relative; top: -3px;">
            </a>
       </td>
   </tr>
<nav class="navbar navbar-inverse"...>


      <div class="container-fluid">

        <div class="navbar-header">
            <button
                type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="incon-bar"></span>
                <span class="incon-bar"></span>
                <span class="incon-bar"></span>
            </button>


    <i>
    <a class="navbar-brand" href="{% url 'sedimentos:inicial' %}">SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS</a>
    </i>
        </div>
    </div>
</nav>
<ul class="nav navbar-nav navbar-left">

                <ul><h3> Adicionar: </h3></ul>
    <ul>
              <li class="active">
                    <a href="{% url 'sedimentos:create_amostra'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp; Amostra
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimentos:create_cidade'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp;  Cidade
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimentos:create_estado'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp;  Estado
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimentos:create_país'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp;  País
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimentos:create_continente'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp;  Continente
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimentos:create_ambiente'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp;  Ambiente
                    </a>
                </li>

                 <li class="active">
                    <a href="{% url 'sedimentos:create_clima'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp;  Clima
                    </a>
                </li>
         <h3>Realizar Registro De Usuários Ou Desconectar Do Sistema</h3>
          <ul class="nav navbar-nav navbar-center">
                <li class="">
                    <a href="{% url 'sedimentos:logout_user' %}">
                        <span class="glyphicon glyphicoon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                 </li>
                 <li class="">
                    <a href="{%url 'sedimentos:register' %}">
                        <span class="glyphicon glyphicoon-off" aria-hidden="true"></span>&nbsp; Registrar
                    </a>
                 </li>
    </ul>
    </ul>
</ul>
<br>
<br>
<br>
{% block body %}
{% endblock %}
</body>

</html>
 <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
      <tbody>
        <tr>
            <td align="center">
                <font face="Arial,Hevetica,sans-serif" size="2">
                    <hr size="0">

                      <ul>
                        <i>
                            <a href="http://www5.usp.br/" target="_blank">
                              <img src="/static/sedimentos/imagens/usp.gif" width="150" height="50" alt="" border="0" style="position: relative; top: -3px;">
                            </a>
                            <br>
                            <a href="http://www.igc.usp.br/" target="_blank">Institudo de Geociências/USP</a>
                            <br>
                            <a href="https://www.ime.usp.br/" target="_blank">Instituto de Matemática e Estatística/USP</a>
                           <br>
                           <a href="http://www.prg.usp.br/" target="_blank">Pró-Reitoria de Graduação/USP</a>
                        </i>
                      </ul>
                    <a href="/sedimentos/agradecimentos"  target="_self">Créditos |</a>
                    <a href="/sedimentos/contato">Fale Conosco |</a>
                     <a href="https://github.com/Fabio343/Sediment-Cataloging-System" target="_blank">GitHub</a>
                    <br>

                     © 2016 - 2017  Instituto De Geociências-USP
                    <br>
                    Universidade De São Paulo
                </font>
            </td>
        </tr>
        </tbody>
    </table>

amostras/templates/sedimentos/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS</title>
    {% load staticfiles %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" type="text/css" href="{% static 'sedimentos/style.css' %}"/>
      <script src="https://ajax.googleapis.com/ajax/libs/1.5.7/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
   <tr>
       <td width="180" rowspan="3" align="center">
            <a href="http://www5.usp.br/" target="_blank">
            <img src="/static/sedimentos/imagens/usp.png" width="150" height="70" alt="" border="0" style="position: relative; top: -3px;">

            </a>
       </td>
       <td width="180" rowspan="3" align="center">
            <a href="http://www.igc.usp.br/" target="_blank">
            <img src="/static/sedimentos/imagens/logo_IGc.png" width="150" height="70" alt="" border="0" style="position: relative; top: -3px;">
            </a>
       </td>
       <td width="180" rowspan="3" align="center">
            <a href="https://www.ime.usp.br/" target="_blank">
            <img src="/static/sedimentos/imagens/imeusp.png" width="150" height="70" alt="" border="0" style="position: relative; top: -3px;">
            </a>
       </td>
   </tr>
<nav class="navbar navbar-inverse"...>

      <div role="banner" id="top">
      </div>

    <i>
    <a class="navbar-brand" href="{% url 'sedimentos:inicial' %}">SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS</a>
        <br>
    </i>
        <div class="collapse navbar-collapse" id="topNavBar">
              <ul class="nav navbar-nav">
                  <li class="{% block inicial_active %}{% endblock %}"><a href="{% url 'sedimentos:inicial' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Inicio</a></li>
                   <li class="{% block amostras_active %}{% endblock %}"><a href="{% url 'sedimentos:index' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Amostras</a></li>
                   <li class="{% block continentes_active %}{% endblock %}"><a href="{% url 'sedimentos:continentes' 'all' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Continentes</a></li>
                   <li class="{% block paíss_active %}{% endblock %}"><a href="{% url 'sedimentos:paíss' 'all' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Países</a></li>
                   <li class="{% block estados_active %}{% endblock %}"><a href="{% url 'sedimentos:estados' 'all' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Estados</a></li>
                   <li class="{% block cidades_active %}{% endblock %}"><a href="{% url 'sedimentos:cidades' 'all' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Cidades</a></li>
                   <li class="{% block climas_active %}{% endblock %}"><a href="{% url 'sedimentos:climas' 'all' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Climas</a></li>
                   <li class="{% block ambientes_active %}{% endblock %}"><a href="{% url 'sedimentos:ambientes' 'all' %}"><span class="glyphicon glyphicon-sedimentos" aria-hidden="true"></span>&nbsp; Ambientes</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'sedimentos:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Pesquisar</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li class="">
                    <a href="{% url 'sedimentos:adicionar'%}">
                        <span class="glyphicon glyphicoon-plus" aria-hidden="true"></span>&nbsp;Adicionar
                    </a>
                </li>
                <ul class="nav navbar-nav">
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'sedimentos:login_user' %}">Login</a></li>
                </ul>
              </ul>
        </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>
 <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
     <tbody>
        <tr>
            <td align="center">
                <font face="Arial,Hevetica,sans-serif" size="2">
                    <hr size="0">

                      <ul>
                        <i>
                            <a href="http://www5.usp.br/" target="_blank">
                              <img src="/static/sedimentos/imagens/usp.gif" width="150" height="50" alt="" border="0" style="position: relative; top: -3px;">
                            </a>
                            <br>
                            <a href="http://www.igc.usp.br/" target="_blank">Institudo de Geociências/USP</a>
                            <br>
                            <a href="https://www.ime.usp.br/" target="_blank">Instituto de Matemática e Estatística/USP</a>
                           <br>
                           <a href="http://www.prg.usp.br/" target="_blank">Pró-Reitoria de Graduação/USP</a>
                        </i>
                      </ul>
                    <a href="/sedimentos/agradecimentos"  target="_self">Créditos |</a>
                    <a href="/sedimentos/contato">Fale Conosco |</a>
                     <a href="https://github.com/Fabio343/Sediment-Cataloging-System" target="_blank">GitHub</a>
                    <br>

                     © 2016 - 2017  Instituto De Geociências-USP
                    <br>
                    Universidade De São Paulo
                </font>
            </td>
        </tr>
        </tbody>
    </table>

amostras/templates/sedimentos/contd.html
{% extends 'sedimentos/base.html' %}
{% block title %}{{ continente }}{% endblock %}
{% block continentes_active %}active{% endblock %}
{% block body %}
    <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'sedimentos:detail' amostra.id %}">View All</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All continentes</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>nome</th>
                            <th>sigla</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for continente in amostra.cotinente_set.all %}
                            <tr>
                                <td>{{ continente.nome}}</td>
                                <td>
                                    <form action="{% url 'sedimentos:delete_continente' amostra.id continente.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="continente_id" value="{{ continente.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
{% endblock %}

amostras/templates/sedimentos/inicial.html
{% extends 'sedimentos/base.html' %}
{% block body %}
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h4>Em Que Consiste o Sistema?</h4>
                    <p> É um acervo de exemplares de amostras de sedimentos de diversas regiões do mundo que podem ser usados para estudos,
                        de forma geral sendo principalmente focado em atividades didáticas da área de Geociências. </p>
                    <h4>Quem Pode Acessar?</h4>
                    <p>O acesso é livre a todos, sendo que as funções de alterações de qualquer informação são exclusivas aos administradores do sistema.</p>
                    <h4>Como Realizar Pesquisas?</h4>
                    <ul>
                        <li>Pode realizar a pesquisa por código da amostra, país, cidade, estado, ambiente, clima, entre outros.</li>
                        <li>Ou pode clicar na listagem geral de exemplares</li>
                    </ul>
                    <h4> Quais são as informações apresentadas na lista geral de Exemplares?</h4>
                    <p>Para cada amostra, é fornecida uma descrição geral com informações  como origem, tipo e granulometria</p>
                </div>
            </div>
        </div>
{% endblock %}