catalogação/amostras/urls.py
# urls definidas para as visualizações do sistema cada bloco de url esta definindo quais são as funções de cada uma delas
from django.conf.urls import url
from django.contrib.auth.views import   password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views
from django_filters.views import FilterView
from . filters import amostraFilter

app_name = 'amostras'

urlpatterns = [
   # se refere a pagina inicial e contato com administração/
    url(r'^$', views.index, name='index'),
    url(r'^$', views.amostra, name='amostra'),
    url(r'^contato/$', views.contato),
    url(r'^inicial/$', views.inicial, name='inicial'),

   # se refere a vizualização de detalhes dos exemplares bem como criação de novas amostras e também sua exclusão cada mini bloco representa uma das informações presentes no sistema/
    url(r'^(?P<amostra_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_amostra/$', views.create_amostra, name='create_amostra'),
    url(r'^(?P<amostra_id>[0-9]+)/delete_amostra/$', views.delete_amostra, name='delete_amostra'),

    url(r'^(?P<continente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'continente/add/$', views.create_continente, name='create_continente'),
    url(r'continente/(?P<continente_id>[0-9]+)/$', views.delete_continente, name='delete_continente'),

    url(r'^(?P<cidade_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'cidade/add/$', views.create_cidade, name='create_cidade'),
    url(r'cidade/(?P<cidade_id>[0-9]+)/$', views.delete_cidade, name='delete_cidade'),

    url(r'^(?P<estado_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'estado/add/$', views.create_estado, name='create_estado'),
    url(r'estado/(?P<estado_id>[0-9]+)/$', views.delete_estado, name='delete_estado'),

    url(r'^(?P<país_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'país/add/$', views.create_país, name='create_país'),
    url(r'país/(?P<país_id>[0-9]+)/$', views.delete_país, name='delete_país'),

    url(r'^(?P<ambiente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'ambiente/add/$', views.create_ambiente, name='create_ambiente'),
    url(r'ambiente/(?P<ambiente_id>[0-9]+)/$', views.delete_ambiente, name='delete_ambiente'),

    url(r'^(?P<clima_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'clima/add/$', views.create_clima, name='create_clima'),
    url(r'clima/(?P<clima_id>[0-9]+)/$', views.delete_clima, name='delete_clima'),

    # se refere a login,cadastros,creditos e demais detalhes ao desenvolvimentos/
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^adicionar/$', views.adicionar, name='adicionar'),
    url(r'^agradecimentos/$', views.agradecimentos, name='agradecimentos'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # filtros usados na pesquisa simples/
    url(r'^continentes/(?P<filter_by>[a-zA_Z]+)/$', views.continentes, name='continentes'),
    url(r'^estados/(?P<filter_by>[a-zA_Z]+)/$', views.estados, name='estados'),
    url(r'^cidades/(?P<filter_by>[a-zA_Z]+)/$', views.cidades, name='cidades'),
    url(r'^países/(?P<filter_by>[a-zA_Z]+)/$', views.paíss, name='paíss'),
    url(r'^climas/(?P<filter_by>[a-zA_Z]+)/$', views.climas, name='climas'),
    url(r'^ambientes/(?P<filter_by>[a-zA_Z]+)/$', views.ambientes, name='ambientes'),

    # edição das amostras e perfis de usuarios /
    url(r'^amostra/(?P<pk>\d+)/update/$', views.amostraupdate.as_view(), name='amostraupdate'),
    url(r'^continente/(?P<pk>\d+)/update/$', views.continenteupdate.as_view(), name='continenteupdate'),
    url(r'^país/(?P<pk>\d+)/update/$', views.paísupdate.as_view(), name='paísupdate'),
    url(r'^estado/(?P<pk>\d+)/update/$', views.estadoupdate.as_view(), name='estadoupdate'),
    url(r'^cidade/(?P<pk>\d+)/update/$', views.cidadeupdate.as_view(), name='cidadeupdate'),
    url(r'^clima/(?P<pk>\d+)/update/$', views.climaupdate.as_view(), name='climaupdate'),
    url(r'^ambiente/(?P<pk>\d+)/update/$', views.ambienteupdate.as_view(), name='ambienteupdate'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^change_password/$',views.change_password, name='change_password'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),

   # recuperação de senha  pelo usuario/
    url(r'^reset-password/$', password_reset,
        {'template_name': 'amostras/reset_password.html', 'post_reset_redirect': 'amostras:password_reset_done',
         'email_template_name': 'amostras/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'amostras/reset_password_done.html'},
        name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'amostras/reset_password_confirm.html',
         'post_reset_redirect': 'amostras:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name': 'amostras/reset_password_complete.html'}, name='password_reset_complete'),

    # definições para campos autocomplete para as pesquisas e filtro para pesquisa avançada do sistema/
    url(r'^amostra/autocomplete/', views.amostras, name='amostras'),
    url(r'^grupo_dados/$', views.gru, name='gru'),
    url(r'^grupo/$', views.grupo, name='grupo'),
    url(r'^amostraFilter/$', FilterView.as_view(filterset_class=amostraFilter, template_name='amostras/grupo.html'),
        name='amostraFilter'),

]

catalogação/catalogação/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('amostras.urls')),
    url(r'^amostras/', include('amostras.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogação/amostras/views.py
from django.shortcuts import  render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.views.generic import View
from .models import Amostra
from .models import Continente
from .models import Cidade
from .models import Estado
from .models import País
from .models import Ambiente
from .models import Clima
from .forms import UserForm,amostraForm, continenteForm, paísForm, estadoForm, cidadeForm,climaForm,ambienteForm,EditProfileForm,FormContato
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect
from django.contrib.auth.forms import  PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
import json
from django.http import HttpResponse
from .filters import amostraFilter
from django.shortcuts import render
from django.views.generic.edit import UpdateView

#função para contato com administração
def contato(request):
    if request.method == 'POST':
        form = FormContato(request.POST)

        if form.is_valid():
            form.enviar()
            mostrar = 'Contato enviado!'
            form = FormContato()
    else:
        form = FormContato()
    return render(request,'amostras/contato.html', locals())

########################################################################################################################
# todas a funções abaixo com o termo update são para e edição dos exemplares do sistema
class amostraupdate(UpdateView):
     model = Amostra
     fields = ['codigo', 'coletador', 'Contato', 'descrição', 'tipo', 'data', 'granulometria', 'imagem', 'imagem1',
          'imagem2', 'imagem3',
          'imagem4', 'imagem5', 'imagem6', 'imagem7', 'imagem8', 'Continentes', 'Paíss', 'Estados', 'Cidades',
          'Ambientes', 'Climas']

########################################################################################################################
class continenteupdate(UpdateView):
        model =Continente
        fields = [ 'nome', 'sigla']

########################################################################################################################
class paísupdate(UpdateView):
        model =País
        fields = [ 'nome', 'região','Continentes']

########################################################################################################################
class estadoupdate(UpdateView):
        model =Estado
        fields = [ 'nome','Continentes','Paíss']

########################################################################################################################
class cidadeupdate(UpdateView):
        model =Cidade
        fields = [ 'nome', 'geologia','Continentes','Paíss','Estados']

########################################################################################################################
class ambienteupdate(UpdateView):
        model =Ambiente
        fields = [ 'tipo','Continentes','Paíss','Estados','Cidades']

########################################################################################################################
class climaupdate(UpdateView):
        model =Clima
        fields = [ 'tipo','Continentes','Paíss','Estados','Cidades']

########################################################################################################################
def amostras(request):
  if request.is_ajax():
    q = request.GET.get('term')
    amostras = Amostra.objects.filter(codigo__icontains=q)
    results = []
    for amostra in amostras:
      amostra_json = {}
      amostra_json = amostra.codigo
      results.append(amostra_json)
      data = json.dumps(results)
  else:
    data = 'fail'
  mimetype = 'application/json'
  return HttpResponse(data, mimetype)

########################################################################################################################
def grupo(request):
        grupo = amostraFilter(request.GET, queryset=Amostra.objects.all())
        return render(request, 'amostras/grupo.html', {'filter': grupo})

########################################################################################################################
def gru(request):
    amostras=Amostra.objects.all()
    return render(request,
        "amostras/gru.html",{'amostras':amostras} )
########################################################################################################################
# as funções abaixo definem como são criados os exemplares bem como sua exclusão e visualização de detalhes
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def create_amostra(request):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
        form = amostraForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            amostra = form.save(commit=False)
            amostra.user = request.user
            amostra.save()
            return render(request, 'amostras/detail.html', {'amostra': amostra})
        context = {
            "form": form,
        }
        return render(request, 'amostras/amostra_form.html', context)

def delete_amostra(request, amostra_id):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
     amostra = Amostra.objects.get(pk=amostra_id)
     amostra.delete()
     return render(request, 'amostras/delete.html', {'amostras': amostras})


def detail(request, amostra_id):
        user = request.user
        amostra = get_object_or_404(Amostra, pk=amostra_id)
        return render(request, 'amostras/detail.html', {'amostra': amostra, 'user': user})

########################################################################################################################
########################################################################################################################

def create_continente(request):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
        form = continenteForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            continente = form.save(commit=False)
            continente.user = request.user
            continente.save()
            return render(request, 'amostras/concluido.html', {continente: continente})
        context = {"form": form, }
        return render(request, 'amostras/continente_form.html', context)


def delete_continente(request, continente_id):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
     continente = Continente.objects.get(pk=continente_id)
     continente.delete()
     return render(request, 'amostras/delete.html', {'amostras': amostras})

########################################################################################################################
########################################################################################################################

def create_cidade(request):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
        form = cidadeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            cidade = form.save(commit=False)
            cidade.user = request.user
            cidade.save()
            return render(request, 'amostras/concluido.html', {cidade: cidade})
        context = {
            "form": form,
        }
        return render(request, 'amostras/cidade_form.html', context)


def delete_cidade(request, cidade_id):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
     cidade = Cidade.objects.get(pk=cidade_id)
     cidade.delete()
     return render(request, 'amostras/delete.html', {'amostras': amostras})

########################################################################################################################
########################################################################################################################

def create_estado(request):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
        form = estadoForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            estado = form.save(commit=False)
            estado.user = request.user
            estado.save()
            return render(request, 'amostras/concluido.html', {estado: estado})
        context = {
            "form": form,
        }
        return render(request, 'amostras/estado_form.html', context)


def delete_estado(request, estado_id):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
     estado = Estado.objects.get(pk=estado_id)
     estado.delete()
     return render(request, 'amostras/delete.html', {'amostras': amostras})

########################################################################################################################
########################################################################################################################

def create_país(request):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
        form = paísForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            país = form.save(commit=False)
            país.user = request.user
            país.save()
            return render(request, 'amostras/concluido.html', {país: país})
        context = {
            "form": form,
        }
        return render(request, 'amostras/país_form.html', context)


def delete_país(request, país_id):
    if not request.user.is_authenticated():
        return render(request, 'amostras/login.html')
    else:
     país = País.objects.get(pk=país_id)

catalogação/amostras/templates/amostras/adicionar.html
<!--Sessão responsável por funções de adição de dados ao banco de  dados bem como a visualização de informações cdo usuário logado ou a edição dos mesmos, é a pagina de administração geral
do sistema web-->
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
         {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'amostras/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=0.65">
        {% block head %}
        <title>Sistema de Catalogação</title>
        {% endblock %}
      </head>
      <section class="container-fluid ">
      <body>
         <br>
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
         <tr>
         <td width="180" rowspan="3" align="center">
            <a href="http://www5.usp.br/" target="_blank">
            <img src="/static/amostras/imagens/usp.png" width="100" height="50" alt="" border="0" style="position: relative; top: 3px;">

            </a>
         </td>
         <td width="180" rowspan="3" align="center">
            <a href="http://www.igc.usp.br/" target="_blank">
            <img src="/static/amostras/imagens/logoigc.png" width="165" height="50" alt="" border="0" style="position: relative; top: 3px;">
            </a>
         </td>
         <td width="180" rowspan="3" align="center">
            <a href="https://www.ime.usp.br/" target="_blank">
             <img src="/static/amostras/imagens/imeusp.png" width="60" height="60" alt="" border="0" style="position: relative; top: 3px;">
            </a>
         </td>
         </tr>
          <br>
        <i>
        <a class="navbar-brand" href="{% url 'amostras:inicial' %}">SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS</a>
        <br>
        </i>

              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li class="{% block inicial_active %}{% endblock %}"><a href="{% url 'amostras:inicial' %}"><span class="glyphicon glyphico-amostras" aria-hidden="true"></span>&nbsp; Inicio</a></li>
                  </ul>
              </div>
              </section>
              <br>


        <ul class="nav navbar-nav navbar-left">

                <ul><h4> Adicionar: </h4></ul>

              <li class="active">
                    <a href="{% url 'amostras:create_amostra'%}">
                         <button type="submit">&nbsp; Amostra </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'amostras:create_cidade'%}">
                         <button type="submit">&nbsp;  Cidade </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'amostras:create_estado'%}">
                         <button type="submit">&nbsp;Estado </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'amostras:create_país'%}">
                         <button type="submit">&nbsp;País </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'amostras:create_continente'%}">
                         <button type="submit">&nbsp;Continente </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'amostras:create_ambiente'%}">
                         <button type="submit">&nbsp;Ambiente </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'amostras:create_clima'%}">
                         <button type="submit">&nbsp;Clima </button>
                    </a>
                </li>
            <br>
            <br>
            <ul><h4>Registrar Usuario: </h4></ul>
            <ul class="nav navbar-nav navbar-center">
                 <li class="">
                    <a href="{%url 'amostras:register' %}">
                         <button type="submit">&nbsp;Registrar </button>
                    </a>
                 </li>
            </ul>
            <br>
            <br>
            <br>
            <ul><h4>Alterar Suas Informações:</h4></ul>
            <ul class="nav navbar-nav navbar-center">
                    <li><a href="{% url 'amostras:edit_profile' %}">
                         <button type="submit">Editar Pefil</button></a></li>
                    <li><a href="{% url 'amostras:change_password' %}">
                         <button type="submit">Alterar Senha</button></a></li>
            </ul>

           <li class="active">
            <a href="{% url 'amostras:gru'%}">
             <button type="submit">&nbsp;Visualização Geral</button>
            </a>
          </li>
        </ul>
           <div class="col-sm-5 col-md-4">
               <div class="panel panel-default">
                   <div class="panel-body">
                         <title>Perfil do Usuário</title>
                         <div class="container">
                                <h3>Perfil do Usuário:</h3>
                                   <h5><p>Nome: {{ user.first_name }}</p>
                                   <p>Sobrenome: {{ user.last_name }}</p>
                                   <p>Nome de Usuário: {{ user }}</p>
                                   <p>Email: {{ user.email }}</p><h5>
                                <li class="">
                                   <a href="{% url 'amostras:logout_user' %}">
                                        <button type="submit">Sair</button>
                                   </a>
                                </li>
                         </div>
                   </div>
               </div>
           </div>
      </body>

      <script
        src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
        crossorigin="anonymous">
      </script>

      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>
<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
     <tbody>
        <tr>
            <td align="center">
                <font face="Arial,Hevetica,sans-serif" size="2">
                    <hr size="0">

                      <ul>
                        <i>

                            <a href="http://www5.usp.br/" target="_blank">
                              <img src="/static/amostras/imagens/usp.gif" width="150" height="50" alt="" border="0" style="position: relative; top: -3px;">
                            </a>
                            <br>
                            <a href="http://www.igc.usp.br/" target="_blank">Institudo de Geociências/USP</a>
                            <br>
                            <a href="https://www.ime.usp.br/" target="_blank">Instituto de Matemática e Estatística/USP</a>
                           <br>
                           <a href="http://www.prg.usp.br/" target="_blank">Pró-Reitoria de Graduação/USP</a>
                        </i>
                      </ul>
                    <a href="/amostras/agradecimentos"  target="_self">Créditos |</a>
                    <a href="/amostras/contato"> Fale Conosco |</a>
                     <a href="https://github.com/Fabio343/Sediment-Cataloging-System" target="_blank">GitHub</a>
                    <br>
                     © 2016 - 2017  Instituto De Geociências-USP
                    <br>
                    Universidade De São Paulo
                </font>
            </td>
        </tr>
        </tbody>

</table>

catalogação/amostras/templates/amostras/change_password.html
{% extends 'amostras/basevisitante.html' %}
{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
   <div class="col-sm-3">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Concluir</button>
    </form>
   </div>
</div>

{% endblock %}

catalogação/amostras/templates/amostras/contact.html
{% extends 'amostras/base2.html' %}

{% block body %}
<ul><h3>Contato com a administração</h3></ul>
  <div class="col-sm-2">
    <ul>
      <form role="form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Concluir</button>
      </form>
    </ul>
  </div>
{% endblock %}

catalogação/amostras/templates/amostras/pesquisa.html
{% extends 'amostras/base2.html' %}
{% block body %}
   {% if amostras %}
         <div class="row">
            <div class="col-sm-12">
              <ul>
                 <h3> Amostras :</h3>
              </ul>
            </div>
            <ul>
              {% for amostra in amostras %}

                <div class="col-sm-3 col-lg-2">
                    <div class="thumbnail">

                        <a href="{% url 'amostras:detail' amostra.id %}">

                          {% if amostra.imagem %}
                             <img src="{{ amostra.imagem.url }}" class="img-responsive">
                            {% else %}
                          {% endif %}
                          {% if amostra.granulometria %}
                               <img src="{{ amostra.granulometria.url }}" class="img-responsive" style="width: 500px; float:left; margin-right: 500px;">
                          {% else %}
                          {% endif %}
                        </a>
                        <div class="caption">
                            <h3>{{ amostra.codigo }}</h3>
                            <h4>{{ amostra.tipo }}</h4>

                            <!-- Ver Detalhes -->
                            <a href="{% url 'amostras:detail' amostra.id %}" class="btn btn-primary btn-sm" role="button">Detalhes</a>

                                {% if user.is_authenticated %}
                                   <a href="{% url 'amostras:amostraupdate' amostra.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                                   <!-- Delete amostra -->
                                   <a href="#janela8" class="glyphicon glyphicon-trash" rel="modal"></a>
		                                <div class="window" id="janela8">
		        	                       <a href="#" class="fechar">X Fechar</a>
                                           <h5>Deseja realmente excluir?</h5>
                                          <form action="{% url 'amostras:delete_amostra' amostra.id %}" method="post" style="display: inline;">
                                              {% csrf_token %}
                                              <input type="hidden" name="amostra_id" value="{{ amostra.id }}" />
                                              <button type="submit" class="btn btn-default btn-sm">
                                                  <span class="glyphicon glyphicon-trash"></span>
                                              </button>
                                          </form>
                                        </div>
                                {% else %}
                                {% endif %}
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
              {% endfor %}
            </ul>
         </div>
   {% endif %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.1/jquery.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){
				$("a[rel=modal]").click( function(ev){
					ev.preventDefault();

					var id = $(this).attr("href");

					var alturaTela = $(document).height();
					var larguraTela = $(window).width();

					//colocando o fundo preto
					$('#mascara').css({'width':larguraTela,'height':alturaTela});
					$('#mascara').fadeIn(1000);
					$('#mascara').fadeTo("slow",0.8);

					var left = ($(window).width() /2) - ( $(id).width() / 2 );
					var top = ($(window).height() / 2) - ( $(id).height() / 2 );

					$(id).css({'top':top,'left':left});
					$(id).show();
 				});

 				$("#mascara").click( function(){
 					$(this).hide();
 					$(".window").hide();
 				});

 				$('.fechar').click(function(ev){
 					ev.preventDefault();
 					$("#mascara").hide();
 					$(".window").hide();
 				});
			});
		</script>

		<style type="text/css">

		.window{
			display:none;
			width:300px;
			height:300px;
			position:absolute;
			left:0;
			top:0;
			background:#FFF;
			z-index:9900;
			padding:10px;
			border-radius:10px;
		}

		#mascara{
			position:absolute;
  			left:0;
  			top:0;
  			z-index:9000;
  			background-color:#000;
  			display:none;
		}

		.fechar{display:block; text-align:right;}

		</style>

  {% if amostras.has_other_pages %}
    <ul class="pagination">
      {% if amostras.has_previous %}
        <li><a href="?page={{ amostras.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in amostras.paginator.page_range %}
        {% if amostras.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
         <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if amostras.has_next %}
        <li><a href="?page={{ amostras.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
     </ul>
  {% endif %}
</div>
{% endblock %}