amostras/amostras/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sedimentos/', include('sedimentos.urls')),
    url(r'^',include('sedimentos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amostras/sedimentos/urls.py
from django.conf.urls import url
from . import views

app_name = 'sedimentos'

urlpatterns = [

    # se refere a /resident/
    url(r'^$', views.index, name='index'),
    url(r'^$', views.amostra, name='amostra'),
    # se refere a uma em especifico/
    url(r'^(?P<amostra_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_amostra/$', views.create_amostra, name='create_amostra'),
    url(r'^(?P<amostra_id>[0-9]+)/delete_amostra/$', views.delete_amostra, name='delete_amostra'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),


    # se refere a uma em especifico/
    url(r'^(?P<continente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'continente/add/$', views.create_continente, name='create_continente'),
    url(r'continente/(?P<pk>[0-9]+)/$', views.delete_continente, name='delete_continente'),


    # se refere a uma em especifico/
    url(r'^(?P<cidade_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'cidade/add/$', views.create_cidade, name='create_cidade'),
    url(r'cidade/(?P<pk>[0-9]+)/$', views.delete_cidade, name='delete_cidade'),


    # se refere a uma em especifico/
    url(r'^(?P<estado_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'estado/add/$', views.create_estado, name='create_estado'),
    url(r'estado/(?P<pk>[0-9]+)/$', views.delete_estado, name='delete_estado'),


    # se refere a uma em especifico/
    url(r'^(?P<país_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'país/add/$', views.create_país, name='create_país'),
    url(r'país/(?P<pk>[0-9]+)/$', views.delete_país, name='delete_país'),

    # se refere a uma em especifico/
    url(r'^(?P<ambiente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'ambiente/add/$', views.create_ambiente, name='create_ambiente'),
    url(r'ambiente/(?P<pk>[0-9]+)/$', views.delete_ambiente, name='delete_ambiente'),

    # se refere a uma em especifico/
    url(r'^(?P<clima_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'clima/add/$', views.create_clima, name='create_clima'),
    url(r'clima/(?P<pk>[0-9]+)/$', views.delete_clima, name='delete_clima'),

    # se refere a uma em especifico/
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^inicial/$', views.inicial, name='inicial'),
    url(r'^contato/$', views.contato, name='contato'),
    url(r'^adicionar/$', views.adicionar, name='adicionar'),
    url(r'^agradecimentos/$', views.agradecimentos, name='agradecimentos'),
    url(r'^register/$', views.register, name='register'),
    # filtros/
    url(r'^continentes/(?P<filter_by>[a-zA_Z]+)/$', views.continentes, name='continentes'),
    url(r'^estados/(?P<filter_by>[a-zA_Z]+)/$', views.estados, name='estados'),
    url(r'^cidades/(?P<filter_by>[a-zA_Z]+)/$', views.cidades, name='cidades'),
    url(r'^paíss/(?P<filter_by>[a-zA_Z]+)/$', views.paíss, name='paíss'),
    url(r'^climas/(?P<filter_by>[a-zA_Z]+)/$', views.climas, name='climas'),
    url(r'^ambientes/(?P<filter_by>[a-zA_Z]+)/$', views.ambientes, name='ambientes'),
    url(r'^amostras/(?P<filter_by>[a-zA_Z]+)/$', views.amostras, name='amostras'),

]


amostras/sedimentos/models.py
# Create your models here.

from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
from django.db import models





# Create your models here.
class Amostra(models.Model):
    user = models.ForeignKey(User, default=1)
    codigo=models.CharField(max_length=15,unique=True)
    tipo = models.CharField(max_length=25)
    descrição=models.TextField(max_length=300,blank=True,null=True)
    data=models.CharField(max_length=15,blank=True,null=True)
    granulometria=models.FileField(null=True,blank=True)
    coletador=models.CharField(max_length=50,blank=True,null=True)
    imagem = models.FileField(null=True,blank=True)
    imagem1 = models.FileField(null=True, blank=True)
    imagem2 = models.FileField(null=True, blank=True)
    imagem3 = models.FileField(null=True, blank=True)
    imagem4 = models.FileField(null=True, blank=True)
    imagem5 = models.FileField(null=True, blank=True)
    imagem6 = models.FileField(null=True, blank=True)
    imagem7 = models.FileField(null=True, blank=True)
    imagem8 = models.FileField(null=True, blank=True)



    def get_absolute_url(self):
        return reverse('sedimentos:detail',kwargs={'pk': self.pk})
    def __str__(self):
        return self.codigo +' - '+self.tipo
    def __unicode__(self):
        if self.descrição:
            return "%s, %s, %s, %s, %s, %s" % (self.codigo, self.tipo,self.descrição, self.data, self.granulometria, self.coletador)
        else:
           return "%s, %s, %s, %s, %s" % (self.codigo, self.tipo, self.data, self.granulometria, self.coletador)




class Continente(models.Model):
    amostra=models.ForeignKey(Amostra,on_delete=models.CASCADE)
    nome=models.CharField(max_length=25)
    sigla=models.CharField(max_length=10)
    is_destaque=models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('sedimentos:detail', kwargs={'pk': self.pk})
    def __str__(self):
       return self.nome




class País(models.Model):
    amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    continente = models.ForeignKey(Continente, on_delete=models.CASCADE)
    nome=models.CharField(max_length=35)
    região=models.CharField(max_length=25,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('sedimentos:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.nome+' - '+self.região
    def __unicode__(self):
        if self.região:
            return "%s, %s" % (self.nome,self.região)
        else:
           return "%s" % (self.nome)



class Estado(models.Model):
    amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    continente = models.ForeignKey(Continente, on_delete=models.CASCADE)
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    nome=models.CharField(max_length=55,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('sedimentos:detail', kwargs={'pk': self.pk})
    def __str__(self):
         return self.nome


class Cidade(models.Model):
    amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    continente = models.ForeignKey(Continente, on_delete=models.CASCADE)
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    nome=models.CharField(max_length=55,blank=True,null=True)
    geologia=models.TextField(max_length=300,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('sedimentos:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.nome
    def __unicode__(self):
        if self.geologia:
            return "%s, %s" % (self.nome,self.geologia)
        else:
           return "%s" % (self.nome)


class Ambiente(models.Model):
    amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    continente = models.ForeignKey(Continente, on_delete=models.CASCADE)
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
    tipo=models.CharField(max_length=30,blank=True,null=True)

    def get_absolute_url(self):
        return reverse('sedimentos:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.tipo


class Clima(models.Model):
    amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    continente = models.ForeignKey(Continente, on_delete=models.CASCADE)
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
    tipo=models.CharField(max_length=40,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('sedimentos:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.tipo

amostras/sedimentos/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Amostra,Continente,País,Estado,Cidade,Ambiente,Clima



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']



class ContatoForm(forms.Form):
    Nome = forms.CharField(label='Nome', max_length=100, required=True)
    Email = forms.EmailField(label=' Email', max_length=200, required=True)
    Mensagem = forms.CharField(label=' Mensagem', min_length=100, required=True, widget=forms.Textarea)




class amostraForm(forms.ModelForm):
    class Meta:
        model =Amostra
        fields = ['codigo','coletador', 'descrição', 'tipo', 'data', 'granulometria','imagem','imagem1','imagem2','imagem3','imagem4','imagem5','imagem6','imagem7','imagem8']



class continenteForm(forms.ModelForm):
    class Meta:
        model =Continente
        fields = ['amostra', 'nome', 'sigla']



class paísForm(forms.ModelForm):
    class Meta:
        model =País
        fields = ['amostra', 'continente', 'nome', 'região']



class estadoForm(forms.ModelForm):
    class Meta:
        model =Estado
        fields = ['amostra', 'continente', 'país', 'nome']



class cidadeForm(forms.ModelForm):
    class Meta:
        model =Cidade
        fields = ['amostra', 'continente', 'país', 'estado', 'nome', 'geologia']



class ambienteForm(forms.ModelForm):
    class Meta:
        model =Ambiente
        fields = ['amostra', 'continente', 'país', 'estado', 'cidade', 'tipo']




class climaForm(forms.ModelForm):
    class Meta:
        model =Clima
        fields = ['amostra', 'continente', 'país', 'estado', 'cidade', 'tipo']

amostras/sedimentos/templates/sedimentos/agradecimentos.html
{% extends 'sedimentos/basevisitante.html' %}
{% load static %}
<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'sedimentos/../../static/css/agradecimentos.css' %}">

    <title>Créditos</title>
</head>
{% block body %}
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h4>Desenvolvimento:</h4>
                       <li>Fabio Carvalho de Souza; Aluno de Graduação, Matemática Aplicada e Computacional IME-USP</li>
                    <h4>Professor(a) Orientador(a)do Projeto:</h4>
                       <li>Christine Laure Marie Bourotte; Professora do Departamento de Geologia Sedimentar e Ambiental IGC-USP</li>
                    <h4>Professor(a) Orientador(a)do Projeto:</h4>
                       <li>Kelly Rosa Braghetto; Professora Doutora Do Departamento de Ciência Da Computação IME-USP</li>
                    <h4>Progama de Bolsas Unificadas USP: </h4>

                        <li>Projeto: Desenvolvimento De Um Banco De Dados Sistematizado Para A Coleção De Areias Utilizada Para Fins Didáticos E De Difusão Em Geociências</li>

                </div>
            </div>
            <ul>
               <a href="/inicial">Volte a Página do Sistema</a>
            </ul>
        </div>

{% endblock %}

amostras/sedimentos/templates/sedimentos/basevisitante.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block tutle %}SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=arial' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'sedimentos/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
  <nav class="navbar navbar-inverse"...>
      <div class="container-fluid">

        <div class="navbar-header">
            <button
                type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="incon-bar"></span>
                <span class="incon-bar"></span>
                <span class="incon-bar"></span>
            </button>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}"> UNIVERSIDADE DE SÃO PAULO </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}"> Instituto de Geociências (IGC-USP)  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}"> Instituto de Matemática e Estatística (IME-USP) </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}"> Programa de Bolsas Unificadas(PBU) </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
             <a class="navbar-brand" href="{% url 'sedimentos:index' %}">  </a>
        </div>
  </nav>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">


        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'sedimentos:index' %}">SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS</a>
        </div>


        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'sedimentos:login_user' %}">Login</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

amostras/sedimentos/templates/sedimentos/detail2.html
{% extends 'sedimentos/base.html' %}
{% block title %}{{ continente }}{% endblock %}
{% block continentes_active %}active{% endblock %}
{% block body %}
<div class="panel panel-default">

<ul>
    {% for amostra in continente.amostra_set.all %}
           <h3>{{amostra.codigo}}</h3>
           <li>{{amostra.tipo}}</li>
           <li>{{amostra.descrição}}</li>
           <li>{{amostra.granulometria}}</li>
           <li>{{amostra.data}}</li>
           <li>{{amostra.coletador}}</li>
    {% endfor %}

       {% for cidade in continente.cidade_set.all %}
          <h3>{{cidade.amostra}}</h3>
    Cidade de Coleta:
           <li>{{cidade.nome}}</li>
    Geologia Local:
           <li>{{cidade.geologia}}</li>
    {% endfor %}

    {% for estado in continente.estado_set.all %}
     Estado de Coleta:
    <li>{{estado.nome}}</li>
    {% endfor %}

    {% for ambiente in continente.ambiente_set.all %}
    Ambiente de Coleta :
    <li>{{ambiente.tipo}}</li>
    {% endfor %}

    {% for país in continente.país_set.all %}
    País de coleta:
    <li>{{país.nome}}</li>
    {% endfor %}

    {% for clima in continente.clima_set.all %}
    Clima da Região:
    <li>{{clima.tipo}}</li>
    {% endfor %}
</ul>

</div>
{% endblock %}

amostras/sedimentos/templates/sedimentos/detail6.html
{% extends 'sedimentos/base.html' %}
{% block title %}{{ ambiente}}{% endblock %}
{% block amostras_active %}active{% endblock %}
{% block body %}
<div class="container-fluid songs-container">

    <div class="row">


        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'sedimentos:detail6' anbiente.id %}">

                    </a>
<ul>
    {% for amostra in ambiente.amostra_set.all %}
           <h3>{{amostra.codigo}}</h3>
           <li>{{amostra.tipo}}</li>
           <li>{{amostra.descrição}}</li>
           <li>{{amostra.granulometria}}</li>
           <li>{{amostra.data}}</li>
           <li>{{amostra.coletador}}</li>
    {% endfor %}
    
    {% for continente in ambiente.continente_set.all %}
    Continente de Origem:
    <li>{{continente.nome}}</li>
    Sigla do Continente:
    <li>{{continente.sigla}}</li>
    {% endfor %}
    
    {% for país in ambiente.país_set.all %}
    País de coleta:
    <li>{{país.nome}}</li>
    {% endfor %}
    
     {% for estado in ambiente.estado_set.all %}
     Estado de Coleta:
    <li>{{estado.nome}}</li>
    {% endfor %}

    {% for clima in ambiente.clima_set.all %}
    Clima da Região:
    <li>{{clima.tipo}}</li>
    {% endfor %}
</ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

amostras/sedimentos/templates/sedimentos/index4.html
{% extends 'sedimentos/base.html' %}
{% block estados_active %}active{% endblock %}

{% block body %}
<div class="estados-container container-fluid">
{% if all_estados %}
   <ul>
        <ul><h3>Todas as estados Disponiveis no Sistema:</h3></ul>
       <ul>
           {% for estado in all_estados %}
            <div class="col-sm-2 col-lg-2">
                <div class="thumbnail">
                   <div class="caption">
                      <a href="{% url 'sedimentos:detail4' estado.id %}">{{estado.nome}}</a>
                        <div class="caption">
                            <h2>{{ estado.nome }}</h2>
                            <h4>{{ estado.país }}</h4>

                            <!-- View Details -->
                             <a href="{% url 'sedimentos:detail4' estado.id %}" class="btn btn-primary btn-sm" role="button">Detalhes</a>

                            <!-- Delete  -->
                            <form action="{% url 'sedimentos:delete_estado' estado.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="estado_id" value="{{ estado.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                   </div>
                </div>
             </div>
            {% endfor %}
        </ul>
   </ul>
</div>
{% endif %}
{% endblock %}

amostras/sedimentos/templates/sedimentos/index5.html
{% extends 'sedimentos/base.html' %}
{% block paíss_active %}active{% endblock %}

{% block body %}
<div class="paíss-container container-fluid">
{% if all_paíss %}
   <ul>
        <ul><h3>Todas as países Disponiveis no Sistema:</h3></ul>
       <ul>
           {% for país in all_paíss %}
            <div class="col-sm-2 col-lg-2">
                <div class="thumbnail">
                   <div class="caption">
                      <a href="{% url 'sedimentos:detail3' país.id %}">{{país.nome}}</a>

                        <div class="caption">
                            <h2>{{ país.nome }}</h2>
                            <h4>{{ país.continente }}</h4>

                            <!-- View Details -->
                             <a href="{% url 'sedimentos:detail3' país.id %}" class="btn btn-primary btn-sm" role="button">Detalhes</a>

                            <!-- Delete -->
                            <form action="{% url 'sedimentos:delete_país' país.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="país_id" value="{{ país.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                   </div>
                </div>
             </div>
            {% endfor %}
        </ul>
   </ul>
</div>
{% endif %}
{% endblock %}

amostras/sedimentos/templates/sedimentos/index6.html
{% extends 'sedimentos/base.html' %}
{% block ambientes_active %}active{% endblock %}

{% block body %}
<div class="ambientes-container container-fluid">
{% if all_ambientes %}
   <ul>
        <ul><h3>Todas os ambientes Disponiveis no Sistema:</h3></ul>
       <ul>
           {% for ambiente in all_ambientes %}
            <div class="col-sm-2 col-lg-2">
                <div class="thumbnail">
                   <div class="caption">
                      <a href="{% url 'sedimentos:detail6' ambiente.id %}">{{ambiente.tipo}}</a>

                        <div class="caption">
                            <h2>{{ ambiente.tipo }}</h2>
                            <h4>{{ ambiente.amostra }}</h4>

                            <!-- View Details -->
                             <a href="{% url 'sedimentos:detail6' ambiente.id %}" class="btn btn-primary btn-sm" role="button">Detalhes</a>

                            <!-- Delete  -->
                            <form action="{% url 'sedimentos:delete_ambiente' ambiente.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="ambiente_id" value="{{ ambiente.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                   </div>
                </div>
             </div>
            {% endfor %}
        </ul>
   </ul>
</div>
{% endif %}
{% endblock %}


amostras/sedimentos/templates/sedimentos/index7.html
{% extends 'sedimentos/base.html' %}
{% block climas_active %}active{% endblock %}

{% block body %}
<div class="climas-container container-fluid">
{% if all_climas %}
   <ul>
        <ul><h3>Todas os aclimas Disponiveis no Sistema:</h3></ul>
       <ul>
           {% for clima in all_climas %}
            <div class="col-sm-2 col-lg-2">
                <div class="thumbnail">
                   <div class="caption">
                      <a href="{% url 'sedimentos:detail7' clima.id %}">{{clima.tipo}}</a>

                        <div class="caption">
                            <h2>{{ clima.tipo }}</h2>
                            <h4>{{ clima.amostra }}</h4>

                            <!-- View Details -->
                             <a href="{% url 'sedimentos:detail7' clima.id %}" class="btn btn-primary btn-sm" role="button">Detalhes</a>

                            <!-- Delete  -->
                            <form action="{% url 'sedimentos:delete_clima' clima.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="clima_id" value="{{ clima.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                   </div>
                </div>
             </div>
            {% endfor %}
        </ul>
   </ul>
</div>
{% endif %}
{% endblock %}

amostras/sedimentos/templates/sedimentos/país_form.html

{% extends 'sedimentos/base.html' %}
{% block paíss_active %} active {% endblock %}

{%block body %}
<div class="paíss-container container-fluid">

    <div class="row">

        <div class="col-sm-4 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>País</h2>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        {% include 'sedimentos/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-sucess">concluir</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}