se/se/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sedimento/', include('sedimento.urls')),
    url(r'^',include('sedimento.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

se/sedimento/urls.py
from django.conf.urls import url
#from django_filters.views import FilterView
from django.contrib.auth.views import   password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views
#from .filters import amostraFilter

app_name = 'sedimento'

urlpatterns = [
    # listagem geral
    url(r'^lista_continente/', views.lista_continente),
    url(r'^lista_país/', views.lista_país),
    url(r'^lista_estado/', views.lista_estado),
    url(r'^lista_cidade/', views.lista_cidade),
    url(r'^lista_ambiente/', views.lista_ambiente),
    url(r'^lista_clima/', views.lista_clima),

   # se refere a detalhes gerais e apresentação inicial do site /
    url(r'^$', views.index, name='index'),
    url(r'^$', views.amostra, name='amostra'),

    # se refere a criação e exclusão de amostras/
    url(r'^(?P<amostra_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_amostra/$', views.create_amostra, name='create_amostra'),
    url(r'^(?P<amostra_id>[0-9]+)/delete_amostra/$', views.delete_amostra, name='delete_amostra'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # se refere a detalhes de criação e exclusão de continentes/
    url(r'^(?P<continente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'continente/add/$', views.create_continente, name='create_continente'),
    url(r'continente/(?P<continente_id>[0-9]+)/$', views.delete_continente, name='delete_continente'),

    # se refere a detalhes de criação e exclusão de cidades/
    url(r'^(?P<cidade_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'cidade/add/$', views.create_cidade, name='create_cidade'),
    url(r'cidade/(?P<cidade_id>[0-9]+)/$', views.delete_cidade, name='delete_cidade'),

    # se refere a detalhes de criaçãoe exclusão de estados/
    url(r'^(?P<estado_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'estado/add/$', views.create_estado, name='create_estado'),
    url(r'estado/(?P<estado_id>[0-9]+)/$', views.delete_estado, name='delete_estado'),

    # se refere a detalhes de crianção e exclusão de paises/
    url(r'^(?P<país_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'país/add/$', views.create_país, name='create_país'),
    url(r'país/(?P<país_id>[0-9]+)/$', views.delete_país, name='delete_país'),

    # se refere a detalhes de criação  e exclusão de ambientes /
    url(r'^(?P<ambiente_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'ambiente/add/$', views.create_ambiente, name='create_ambiente'),
    url(r'ambiente/(?P<ambiente_id>[0-9]+)/$', views.delete_ambiente, name='delete_ambiente'),

    # se refere a detalhes de criação e exclusão de climas/
    url(r'^(?P<clima_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'clima/add/$', views.create_clima, name='create_clima'),
    url(r'clima/(?P<clima_id>[0-9]+)/$', views.delete_clima, name='delete_clima'),

    # se refere a login,cadastros,creditos e demais detalhes ao desenvolvimento/
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^inicial/$', views.inicial, name='inicial'),
    url(r'^contato/$', views.contato, name='contato'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^adicionar/$', views.adicionar, name='adicionar'),
    url(r'^agradecimentos/$', views.agradecimentos, name='agradecimentos'),
    url(r'^register/$', views.register, name='register'),

    # filtros para as pesquisas de modo que aceita qualquer informação  de modo a levar ao usuario que realiza pesquisa
    # a melhor e mais proxima que seja a informação que ele se referiu/
    url(r'^continentes/(?P<filter_by>[a-zA_Z]+)/$', views.continentes, name='continentes'),
    url(r'^estados/(?P<filter_by>[a-zA_Z]+)/$', views.estados, name='estados'),
    url(r'^cidades/(?P<filter_by>[a-zA_Z]+)/$', views.cidades, name='cidades'),
    url(r'^paíss/(?P<filter_by>[a-zA_Z]+)/$', views.paíss, name='paíss'),
    url(r'^climas/(?P<filter_by>[a-zA_Z]+)/$', views.climas, name='climas'),
    url(r'^ambientes/(?P<filter_by>[a-zA_Z]+)/$', views.ambientes, name='ambientes'),
    url(r'^amostras/(?P<filter_by>[a-zA_Z]+)/$', views.amostras, name='amostras'),

    # edição de informações de amostras,contientes... visualização de informações de administradores , além da  recuperação de informações como senha/
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^amostra-edit/(?P<amostra_id>[0-9]+)/edit/$', views.amostra_edit, name='amostra_edit'),
    url(r'^continente-edit/(?P<continente_id>[0-9]+)/edit/$', views.continente_edit, name='continente_edit'),
    url(r'^país-edit/(?P<país_id>[0-9]+)/edit/$', views.país_edit, name='país_edit'),
    url(r'^estado-edit/(?P<estado_id>[0-9]+)/edit/$', views.estado_edit, name='estado_edit'),
    url(r'^cidade-edit/(?P<cidade_id>[0-9]+)/edit/$', views.cidade_edit, name='cidade_edit'),
    url(r'^clima-edit/(?P<clima_id>[0-9]+)/edit/$', views.clima_edit, name='clima_edit'),
    url(r'^ambiente-edit/(?P<ambiente_id>[0-9]+)/edit/$', views.ambiente_edit, name='ambiente_edit'),

    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^change_password/$',views.change_password, name='change_password'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),


    url(r'^reset-password/$', password_reset,
        {'template_name': 'sedimento/reset_password.html', 'post_reset_redirect': 'sedimento:password_reset_done',
         'email_template_name': 'sedimento/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'sedimento/reset_password_done.html'},
        name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'sedimento/reset_password_confirm.html',
         'post_reset_redirect': 'sedimento:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name': 'sedimento/reset_password_complete.html'}, name='password_reset_complete'),

    # definições para campos autocomplete para as pesquisas

    url(r'^autoamostras/$',views.autoamostras),
    url(r'^autopaís/$',views.autopais),
    url(r'^autoestado/$',views.autoestado),
    url(r'^autocidade/$', views.autocidade),
    url(r'^autoambiente/$', views.autoambiente),
   # url(r'^filtro/$', FilterViews.as_view(filterset_class=amostraFilter,tempalte_name='sedimentos/amostra_list.html'),name='filtro'),
]

se/sedimento/models.py
from django.db import models

# Create your models here.
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
from django.db import models





# Create your models here.


class Continente(models.Model):
    nome=models.CharField(max_length=25)
    is_destaque=models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('sedimento:detail', kwargs={'pk': self.pk})
    def __str__(self):
       return self.nome




class País(models.Model):

    nome=models.CharField(max_length=35)
    região=models.CharField(max_length=25,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)

    Continentes=models.ManyToManyField(Continente,through='Conti_país',blank=True)

    def get_absolute_url(self):
        return reverse('sedimento:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.nome+' - '+self.região
    def __unicode__(self):
        if self.região:
            return "%s, %s" % (self.nome,self.região)
        else:
           return "%s" % (self.nome)

class Conti_país(models.Model):
    continente=models.ForeignKey(Continente,on_delete=models.CASCADE)
    país=models.ForeignKey(País,on_delete=models.CASCADE)

class Estado(models.Model):

    nome=models.CharField(max_length=55,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)
    Paíss = models.ManyToManyField(País,through='País_estado',blank=True)

    def get_absolute_url(self):
        return reverse('sedimento:detail', kwargs={'pk': self.pk})
    def __str__(self):
         return self.nome

class País_estado(models.Model):
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)

class Cidade(models.Model):

    nome=models.CharField(max_length=55,blank=True,null=True)
    geologia=models.TextField(max_length=300,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)

    Paíss = models.ManyToManyField(País ,through='País_estado_cid', blank=True)
    Estados=models.ManyToManyField(Estado ,through='País_estado_cid',blank=True)

    def get_absolute_url(self):
        return reverse('sedimento:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.nome
    def __unicode__(self):
        if self.geologia:
            return "%s, %s" % (self.nome,self.geologia)
        else:
           return "%s" % (self.nome)

class País_estado_cid(models.Model):
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    cidade=models.ForeignKey(Cidade,on_delete=models.CASCADE)


class Ambiente(models.Model):

    tipo=models.CharField(max_length=30,blank=True,null=True)

    Cidades=models.ManyToManyField(Cidade,through='ambi',blank=True)
    def get_absolute_url(self):
        return reverse('sedimento:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.tipo

class ambi(models.Model):
    Cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
    ambiente=models.ForeignKey(Ambiente,on_delete=models.CASCADE)

class Clima(models.Model):

    tipo=models.CharField(max_length=40,blank=True,null=True)
    is_destaque = models.BooleanField(default=False)

    Paíss = models.ManyToManyField(País,through='clim', blank=True)
    Estados = models.ManyToManyField(Estado, through='clim',blank=True)
    Cidades=models.ManyToManyField(Cidade,through='clim',blank=True)

    def get_absolute_url(self):
        return reverse('sedimento:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.tipo

class clim(models.Model):
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
    clima=models.ForeignKey(Clima,on_delete=models.CASCADE)

class Amostra(models.Model):
    user = models.ForeignKey(User, default=1)
    codigo=models.CharField(max_length=15)
    tipo = models.CharField(max_length=25)
    descrição=models.TextField(max_length=300,blank=True,null=True)
    data=models.CharField(max_length=15,blank=True,null=True)
    granulometria=models.FileField(null=True,blank=True)
    coletador=models.CharField(max_length=50,blank=True,null=True)
    imagem = models.FileField(null=True,blank=True)
    imagem1 = models.FileField(null=True, blank=True)
    imagem2 = models.FileField(null=True, blank=True)
    imagem3 = models.FileField(null=True, blank=True)
    imagem4 = models.FileField(null=True, blank=True)
    imagem5 = models.FileField(null=True, blank=True)
    imagem6 = models.FileField(null=True, blank=True)
    imagem7 = models.FileField(null=True, blank=True)
    imagem8 = models.FileField(null=True, blank=True)

    Continentes = models.ManyToManyField(Continente,through='amostr', blank=True)
    Países = models.ManyToManyField(País,through='amostr', blank=True)
    Estados = models.ManyToManyField(Estado,through='amostr', blank=True)
    Cidades = models.ManyToManyField(Cidade,through='amostr', blank=True)
    Ambientes=models.ManyToManyField(Ambiente,through='amostr',blank=True)
    Climas=models.ManyToManyField(Clima,through='amostr',blank=True)

    def get_absolute_url(self):
        return reverse('sedimento:detail',kwargs={'pk': self.pk})
    def __str__(self):
        return self.codigo +' - '+self.tipo
    def __unicode__(self):
        if self.descrição:
            return "%s, %s, %s, %s, %s, %s" % (self.codigo, self.tipo,self.descrição, self.data, self.granulometria, self.coletador)
        else:
           return "%s, %s, %s, %s, %s" % (self.codigo, self.tipo, self.data, self.granulometria, self.coletador)



class amostr(models.Model):
    continente = models.ForeignKey(Continente, on_delete=models.CASCADE)
    país = models.ForeignKey(País, on_delete=models.CASCADE)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
    clima = models.ForeignKey(Clima, on_delete=models.CASCADE)
    ambiente=models.ForeignKey(Ambiente,on_delete=models.CASCADE)
    amostra=models.ForeignKey(Amostra,on_delete=models.CASCADE)

se/sedimento/templates/sedimento/adicionar.html

<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
         {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'sedimento/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=0.65">
        {% block head %}
        <title>Sistema de Catalogação</title>
        {% endblock %}
    </head>
    <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                                          <tr>
       <td width="180" rowspan="3" align="center">
            <a href="http://www5.usp.br/" target="_blank">
            <img src="/static/sedimento/imagens/usp.png" width="100" height="50" alt="" border="0" style="position: relative; top: -3px;">

            </a>
       </td>
       <td width="180" rowspan="3" align="center">
            <a href="http://www.igc.usp.br/" target="_blank">
            <img src="/static/sedimento/imagens/logoigc.png" width="165" height="50" alt="" border="0" style="position: relative; top: -3px;">
            </a>
       </td>
       <td width="180" rowspan="3" align="center">
            <a href="https://www.ime.usp.br/" target="_blank">
             <img src="/static/sedimento/imagens/logoime.png" width="250" height="65" alt="" border="0" style="position: relative; top: -3px;">
            </a>
       </td>
   </tr>
                  <br>
           <i>
    <a class="navbar-brand" href="{% url 'sedimento:inicial' %}">SISTEMA DE CATALOGAÇÃO DE SEDIMENTOS</a>
        <br>
    </i>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <li class="{% block inicial_active %}{% endblock %}"><a href="{% url 'sedimento:inicial' %}"><span class="glyphicon glyphicon-sedimento" aria-hidden="true"></span>&nbsp; Inicio</a></li>
                   <li class="{% block amostras_active %}{% endblock %}"><a href="{% url 'sedimento:index' %}"><span class="glyphicon glyphicon-sedimento" aria-hidden="true"></span>&nbsp; Amostras</a></li>
                   <li> <a href="/lista_continente"><span aria-hidden="true"></span>&nbsp; Continentes</a></li>
                   <li class="{% block paíss_active %}{% endblock %}"> <a href="/lista_país"><span class="glyphicon glyphicon-sedimento" aria-hidden="true"></span>&nbsp; Países</a></li>
                   <li class="{% block estados_active %}{% endblock %}"><a href="/lista_estado"><span class="glyphicon glyphicon-sedimento" aria-hidden="true"></span>&nbsp; Estados</a></li>
                   <li class="{% block cidades_active %}{% endblock %}"> <a href="/lista_cidade"><span class="glyphicon glyphicon-sedimento" aria-hidden="true"></span>&nbsp; Cidades</a></li>
                   <li class="{% block climas_active %}{% endblock %}"><a href="/lista_clima"><span class="glyphicon glyphicon-sedimento" aria-hidden="true"></span>&nbsp; Climas</a></li>
                   <li class="{% block ambientes_active %}{% endblock %}"><a href="/lista_ambiente"><span class="glyphicon glyphicon-sedimento" aria-hidden="true"></span>&nbsp; Ambientes</a></li>
                  </ul>

              <ul class="nav navbar-nav navbar-left">

                <ul><h4> Adicionar: </h4></ul>

              <li class="active">
                    <a href="{% url 'sedimento:create_amostra'%}">
                         <button type="submit">&nbsp; Amostra </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimento:create_cidade'%}">
                         <button type="submit">&nbsp;  Cidade </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimento:create_estado'%}">
                         <button type="submit">&nbsp;Estado </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimento:create_país'%}">
                         <button type="submit">&nbsp;País </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimento:create_continente'%}">
                         <button type="submit">&nbsp;Continente </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimento:create_ambiente'%}">
                         <button type="submit">&nbsp;Ambiente </button>
                    </a>
                </li>
                 <li class="active">
                    <a href="{% url 'sedimento:create_clima'%}">
                         <button type="submit">&nbsp;Clima </button>
                    </a>
                </li>
          <br>
         <ul><h4>Registrar Usuario </h4></ul>
          <ul class="nav navbar-nav navbar-center">
                 <li class="">
                    <a href="{%url 'sedimento:register' %}">
                         <button type="submit">&nbsp;Registrar </button>
                    </a>
                 </li>
          </ul>
         <br>
         <br>
         <br>
         <ul><h4>Alterar Suas Informações</h4></ul>
         <ul class="nav navbar-nav navbar-center">
                    <li><a href="{% url 'sedimento:view_profile' %}">
                         <button type="submit">Perfil</button></a></li>
                    <li><a href="{% url 'sedimento:edit_profile' %}">
                         <button type="submit">Editar Pefil</button></a></li>
                    <li><a href="{% url 'sedimento:change_password' %}">
                         <button type="submit">Alterar Senha</button></a></li>
         </ul>
</ul>
<br>
<br>
<br>

              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
    </body>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
     <tbody>
        <tr>
            <td align="center">
                <font face="Arial,Hevetica,sans-serif" size="2">
                    <hr size="0">

                      <ul>
                        <i>

                            <a href="http://www5.usp.br/" target="_blank">
                              <img src="/static/sedimento/imagens/usp.gif" width="150" height="50" alt="" border="0" style="position: relative; top: -3px;">
                            </a>
                            <br>
                            <a href="http://www.igc.usp.br/" target="_blank">Institudo de Geociências/USP</a>
                            <br>
                            <a href="https://www.ime.usp.br/" target="_blank">Instituto de Matemática e Estatística/USP</a>
                           <br>
                           <a href="http://www.prg.usp.br/" target="_blank">Pró-Reitoria de Graduação/USP</a>
                        </i>
                      </ul>
                    <a href="/sedimento/agradecimentos"  target="_self">Créditos |</a>
                    <a href="/sedimento/contact">Fale Conosco |</a>
                     <a href="https://github.com/Fabio343/Sediment-Cataloging-System" target="_blank">GitHub</a>
                    <br>
                     © 2016 - 2017  Instituto De Geociências-USP
                    <br>
                    Universidade De São Paulo
                </font>
            </td>
        </tr>
        </tbody>

</table>

se/sedimento/templates/sedimento/amostra_form.html
{% extends 'sedimento/base2.html' %}

{% block amostras_active %} active {% endblock %}

{%block body %}
<div class="amostras-container container-fluid">

    <div class="row">

        <div class="col-sm-4 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>Amostra</h2>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        {% include 'sedimento/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-sucess">concluir</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

se/sedimento/templates/sedimento/estado_form.html
{% extends 'sedimento/base2.html' %}
{% block estados_active %} active {% endblock %}

{%block body %}
<div class="estados-container container-fluid">

    <div class="row">

        <div class="col-sm-4 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                     <h2>Estado</h2>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        {% include 'sedimento/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-sucess">concluir</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

se/sedimento/templates/sedimento/lista_ambiente.html
{% extends 'sedimento/base2.html' %}
{% block title %}{{ amostra }}{% endblock %}
{% block amostras_active %}active{% endblock %}

{%block body%}
<div class="row">
 <ul>
      <div class="col-sm-5">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                  <th>Ambiente</th>
                                  <th>Amostra</th>
                            </tr>
                        </thead>
                        <tbody>
                         {% for amostra in amostras %}
      <tr>
                           {% for ambiente in amostra.Ambientes.all %}
                           {% if ambiente.tipo %}
                           <td>{{ambiente.tipo}}</td>
                           {%else%}
                           {%endif%}
                           {% endfor %}
                           {% if amostra.codigo %}
                           <td>{{amostra.codigo}}</td>
                           {%else%}
                           {%endif%}
      </tr>
                         {%endfor%}
                         </tbody>
                    </table>
                </div>
            </div>
      </div>
 </ul>
</div>

{% endblock %}

se/sedimento/templates/sedimento/profile.html
{% extends 'sedimento/basevisitante.html' %}
{% block head %}
<title>Perfil do Usuario</title>
{% endblock %}
{% block body %}
<div class="container">
    <h4>Perfil do Usuario</h4>
    <p>Nome: {{ user.first_name }}</p>
    <p>Sobrenome: {{ user.last_name }}</p>
    <p>Username: {{ user }}</p>
    <p>Email: {{ user.email }}</p>
     <li class="">
     <a href="{% url 'sedimento:logout_user' %}">
         <button type="submit">Logout</button>
     </a>
     </li>
</div>
{% endblock %}

se/sedimento/templates/sedimento/reset_password_complete.html
{% extends 'sedimento/basevisitante.html' %}
{% block body %}
<div class="container">
    <h3>Senha Alterada Com Sucesso</h3>
    <li class="{% block login_active %}{% endblock %}"><a href="{% url 'sedimento:login_user' %}">Login</a></li>
</div>
{% endblock %}

se/sedimento/templates/sedimento/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'sedimento:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Seu nome de usuario caso tenha esquecido:" %} {{ user.get_username }}

{% trans "Obrigado por visitar nosso site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}